<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  <title>アカウント認証</title>
</head>
<body>
  <section class="section">
      <div class="container">
        <h1 class="title">
          <?php echo $msg ?>
        </h1>
<?php if(!$error):?>
          <a href="/" class="button is-info">ログインする</a>
<?php endif ?>
      </div>
  </section>
</body>
</html>