version: '3'
services:
  web:
    build: 
      context: ./docker/Nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - apl
    volumes:
      - public-data:/Ro6MysNgx/public
      - tmp-data:/Ro6MysNgx/tmp
    environment:
      TZ: Asia/Tokyo
  apl:
    build: .
    command: sh docker/Rails6/scripts/launch.sh
    volumes:
      - .:/Ro6MysNgx
      - node:/Ro6MysNgx/node_modules
      - public-data:/Ro6MysNgx/public
      - tmp-data:/Ro6MysNgx/tmp
      - gem_data:/usr/local/bundle
    environment:
      RAILS_ENV: development
      TZ: Asia/Tokyo
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mongo
  db:
    build: 
      context: ./docker/MySQL
    volumes:
      - ./db:/usr/local/share/db
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - "mongo:/data/db"
      - ./configdb:/data/configdb
      - ./import_data:/usr/local/share/db

volumes: 
    db:
    public-data:
    tmp-data:
    node:
    gem_data:
    mongo: